#!/usr/bin/env php
<?php

use Tivins\CIMachine\CLI;
use Tivins\CIMachine\CIMachine;
use Tivins\CIMachine\GitLocation;
use Tivins\Core\Log\CLILogger;
use Tivins\Core\Log\Level;
use Tivins\Core\OptionArg;
use Tivins\Core\OptionsArgs;

require __dir__ . '/../vendor/autoload.php';

$ciCLI  = new CLI();
$logger = new CLILogger();

$options = (new OptionsArgs())
    ->add(new OptionArg('u', true, 'uri'))
    ->add(new OptionArg('b', true, 'branch'))
    ->add(new OptionArg('c', true, 'commit'))
    ->add(new OptionArg('p', true, 'php'))
    ->add(new OptionArg('v', true, 'verbose'))
    ->add(new OptionArg('o', true, 'output'))
    ->add(new OptionArg('h', long: 'help'))
    ->parse();


if (isset($options['help'])) {
    echo $ciCLI->usage();
    exit(0);
}

if (!isset($options['uri'])) {
    $logger->danger("URI is missing");
    echo $ciCLI->usage();
    exit(1);
}

if (isset($options['verbose'])) {
    $logger->setLevel(Level::tryFrom($options['verbose']) ?? Level::DANGER);
}

// -- run --

$machine = new CIMachine(new GitLocation(
    uri:    $options['uri'],
    branch: $options['branch'] ?? GitLocation::BRANCH_DEFAULT,
    commit: $options['commit'] ?? GitLocation::COMMIT_DEFAULT,
));
$machine->setLogger($logger);
if (isset($options['php'])) {
    $machine->setPhpVersion($options['php']);
}
if (isset($options['verbose'])) {
    $machine->setBackupDirectory('/tmp/cim/[uid]');
}
$machine->runBackupClose();
$logger->info($machine->getRealOutDir());
