#!/usr/bin/env php
<?php

use Tivins\CIMachine\CITerminal;
use Tivins\CIMachine\CIMachine;
use Tivins\CIMachine\GitLocation;
use Tivins\Core\Log\CLILogger;
use Tivins\Core\Log\Level;
use Tivins\Core\OptionArg;
use Tivins\Core\OptionsArgs;

require __dir__ . '/../vendor/autoload.php';

$ciCLI  = new CITerminal();
$logger = new CLILogger();
$logger->setLevel(Level::tryFrom($ciCLI->getOption('verbose', Level::DANGER->value)));

if ($ciCLI->hasOption('help')) {
    echo $ciCLI->usage();
    exit(0);
}

if (! $ciCLI->hasOption('uri')) {
    $logger->danger("URI is missing");
    echo $ciCLI->usage();
    exit(1);
}

$location = new GitLocation(
    $ciCLI->getOption('uri', ''),
    $ciCLI->getOption('branch', GitLocation::BRANCH_DEFAULT),
    $ciCLI->getOption('commit', GitLocation::COMMIT_DEFAULT),
);

$machine  = new CIMachine($location);
$machine->setLogger($logger);
$machine->setPhpVersion($ciCLI->getOption('php', CIMachine::PHP_LATEST));
$machine->setBackupDirectory($ciCLI->getOption('output', CIMachine::DEFAULT_DIR));
$machine->doRunBackupClose();
$logger->info($machine->getRealOutDir());
