ARG PHP

FROM debian:11-slim

RUN apt install software-properties-common
RUN add-apt-repository ppa:ondrej/php

# COPY script.php /script

RUN apt update -y ; \
    apt install -y \
      php8.1 \
      zip unzip \
      mariadb-server \
      mariadb-client \
      libsodium-dev \
      libzip-dev \
      curl \
      rsync \
      git
RUN php --version

RUN pecl install xdebug && \
    docker-php-ext-enable xdebug

RUN docker-php-ext-install pdo_mysql

CMD ls -al /run/mysqld/mysqld.sock
RUN service mariadb start

# Composer
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer --version

COPY php.ini /usr/local/etc/php/conf.d/zcover.ini

WORKDIR /box
